import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowIcon } from "../../components/icons";
import { PageShell } from "../../components/site-shell";
import { site } from "../../config/site";
import { careAreas, conditionDetails, getCareArea } from "../care-data";
import { ConditionFlipCard } from "../condition-flip-card";
import { WomensConditionCards } from "../womens-condition-cards";
import womensStyles from "./womens-health-sections.module.css";
import redesignStyles from "./care-redesign.module.css";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return careAreas.map((area)=>({slug:area.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const area=getCareArea(slug);if(!area)return{};return{title:area.seoTitle,description:`${area.summary} Learn about individualized acupuncture care at Springwell Acupuncture in Northern Virginia.`,alternates:{canonical:`/care/${area.slug}`}}}
function AppointmentOptions(){return <section className="section-pad care-appointment-options"><div className="container"><div className="section-heading centered-heading"><p className="eyebrow">Appointment options</p><h2>Simple, unhurried visits.</h2></div><div className="care-appointment-grid"><article><span>New patient</span><h3>Initial consultation + treatment</h3><strong>60–75 min</strong><p>A detailed intake, focused assessment, first treatment, and recommended next steps.</p><a className="text-link" href={site.bookingUrl} target="_blank" rel="noreferrer">Book your first visit <ArrowIcon/></a></article><article><span>Returning patient</span><h3>Follow-up care</h3><strong>45–60 min</strong><p>A progress check, updated treatment focus, and care shaped around your response.</p><a className="text-link" href={site.bookingUrl} target="_blank" rel="noreferrer">Book a follow-up <ArrowIcon/></a></article></div></div></section>}
function TalkSection(){return <section className="care-talk-section"><div className="container"><p className="eyebrow">Have questions?</p><h2>Want to talk?</h2><p>We are offering a free 15-minute consultation for those who are seeking more answers.</p><a className="button button-light" href={site.bookingUrl} target="_blank" rel="noreferrer">Book now <ArrowIcon/></a></div></section>}
const womensHealthDetails = [
  { number: "01", title: "Specialized Training in Women’s Health", copy: "Care at Springwell is informed by graduate training in Traditional Chinese Medicine gynecology. This specialized training shapes our approach to menstrual health, fertility, and reproductive concerns across different stages of life." },
  { number: "02", title: "Traditional Medicine with a Modern Perspective", copy: "Springwell combines traditional Chinese medicine training with a biomedical and research-informed perspective. Treatment is rooted in traditional principles while also considering your medical history, current care, safety, and current evidence around acupuncture." },
  { number: "03", title: "Thoughtful Fertility, IUI & IVF Support", copy: "Fertility care can involve medications, procedures, changing symptoms, and physical and emotional demands. Rather than following a standard protocol, acupuncture is tailored to your individual needs and where you are in your cycle, IUI, or IVF journey, while complementing the care provided by your reproductive medicine team." },
  { number: "04", title: "Looking Beyond a Single Symptom", copy: "At Springwell, we consider the broader clinical picture. Menstrual concerns, fertility, sleep, stress, digestion, pain, and overall wellbeing may overlap, so treatment looks beyond a single symptom when developing an individualized plan." },
] as const;
function WomensHealthDetails(){const left=womensHealthDetails.slice(0,2);const right=womensHealthDetails.slice(2);const renderCard=(card:(typeof womensHealthDetails)[number])=><article key={card.number}><span>{card.number}</span><h3>{card.title}</h3><p>{card.copy}</p></article>;return <section className={womensStyles.detailsSection} aria-labelledby="why-choose-springwell-details"><div className="container"><div className={womensStyles.sectionHeading}><p className="eyebrow">An individualized approach</p><h2 id="why-choose-springwell-details">Why Choose Springwell</h2></div><div className={womensStyles.detailsLayout}><div className={womensStyles.detailsColumn}>{left.map(renderCard)}</div><div className={womensStyles.detailsImage}><Image src="/images/womens-health-pregnancy.webp" alt="Pregnant woman gently holding her belly outdoors" fill quality={90} sizes="(max-width: 860px) 100vw, 34vw" /></div><div className={womensStyles.detailsColumn}>{right.map(renderCard)}</div></div></div></section>}
function PainTreatmentPath(){return <section className="section-pad pain-treatment-path"><div className="container"><div className="care-section-heading"><p className="eyebrow">A focused pain-relief plan</p><h2>Targeted treatment for pain, tension, and movement.</h2><p>Acupuncture can work on several parts of a pain pattern at once: local sensitivity, muscle guarding, nervous-system processing, and the movement habits that keep symptoms going. Many patients notice changes in pain or mobility over a short series of visits, while results vary by condition and person.</p></div><div className="pain-path-grid"><article><span>01</span><h3>Assess the pattern</h3><p>We identify where the pain is, what triggers it, how it changes movement, and whether the symptoms need medical, dental, or physical-therapy evaluation.</p></article><article><span>02</span><h3>Use acupuncture precisely</h3><p>Needles are selected for the painful area and the broader pattern. Local and distal points may be combined to reduce sensitivity and muscle guarding.</p></article><article><span>03</span><h3>Add electroacupuncture</h3><p>For selected chronic or muscular pain patterns, a gentle rhythmic electrical stimulus can extend the treatment input without adding more needles.</p></article><article><span>04</span><h3>Release with cupping</h3><p>When tightness or soreness is prominent, cupping may be added to create a focused decompression and mobility-focused finish.</p></article></div></div></section>}
function StressDomains(){return <section className={redesignStyles.domains}><div className="container"><div className={redesignStyles.domainHeading}><p className="eyebrow">Three connected areas</p><h2>Care that follows the whole pattern.</h2></div><div className={redesignStyles.domainGrid}><article><span>01</span><h3>Stress & nervous-system regulation</h3><p>Support for overwhelm, anxious tension, jaw clenching, and difficulty shifting out of constant demand.</p></article><article><span>02</span><h3>Sleep</h3><p>Care for difficulty falling asleep, waking during the night, restless energy, and unrefreshing rest.</p></article><article><span>03</span><h3>Digestive comfort</h3><p>A whole-person approach to bloating, appetite changes, nausea, and bowel changes that may intensify with stress.</p></article></div></div></section>}
const womensFaqs=[
  ["When should acupuncture begin before IVF?","There is no single schedule that fits every patient. Some begin before a treatment cycle; others seek support during an active cycle. Timing should fit your reproductive specialist’s plan, symptoms, and practical availability."],
  ["Can acupuncture be used during an IVF cycle?","It may be used as supportive care when your reproductive team is informed. Treatment is adjusted around medications, procedures, symptoms, and your clinic’s instructions."],
  ["How often should I come?","Frequency depends on what brings you in, your treatment stage, response, and schedule. We discuss a realistic recommendation after the first assessment and adjust it over time."],
  ["Can acupuncture replace fertility treatment?","No. Acupuncture is supportive care and is not a substitute for evaluation or treatment from a reproductive endocrinologist, OB-GYN, or other qualified medical professional."],
  ["Is acupuncture safe during menstruation?","Acupuncture can generally be adapted during menstruation. Tell your acupuncturist about heavy bleeding, severe or changing pain, pregnancy possibility, medications, and relevant diagnoses."],
  ["Should I tell my fertility specialist?","Yes. Keeping every clinician informed helps coordinate care, avoid conflicts, and ensure that symptoms or medication effects receive appropriate attention."],
] as const;
function WomensFaq(){return <section className={redesignStyles.faq}><div className="container"><div className={redesignStyles.faqHeading}><p className="eyebrow">Women’s health FAQ</p><h2>Common questions about fertility support</h2></div><div className={redesignStyles.faqList}>{womensFaqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>}
const directConditionCardSlugs = new Set(["womens-health-fertility", "pain-management", "stress-sleep"]);
export default async function CareAreaPage({params}:Props){const {slug}=await params;const area=getCareArea(slug);if(!area)notFound();const useDirectConditionCards=directConditionCardSlugs.has(area.slug);return <PageShell><section className="care-page-hero"><div className="care-page-hero-media"><Image src={area.image} alt={area.imageAlt} fill priority quality={95} sizes="100vw"/></div><div className="care-page-hero-overlay"/><div className="container care-page-hero-content"><p className="eyebrow light">{area.eyebrow}</p><h1>{area.title}</h1><p>{area.summary}</p><a className="button button-light" href={site.bookingUrl} target="_blank" rel="noreferrer">Book your first visit <ArrowIcon/></a></div></section>
  {area.slug === "stress-sleep" && <StressDomains/>}
  {area.slug === "womens-health-fertility" ? <WomensHealthDetails/> : area.slug === "pain-management" ? null : <section className="section-pad care-intro-section"><div className="container care-intro-image-grid"><div className={`care-intro-image ${area.slug === "stress-sleep" ? redesignStyles.stressIntroImage : ""}`}><Image src={area.slug === "stress-sleep" ? "/images/stress-mind-line-illustration.webp" : "/images/bringing-balance-back.jpeg"} alt={area.slug === "stress-sleep" ? "Minimal line illustration of a person gently untangling a busy mind" : "Hands gently balancing a stack of smooth stones"} className={area.slug === "stress-sleep" ? redesignStyles.stressIntroArtwork : undefined} fill sizes="(max-width: 860px) 100vw, 42vw" /></div><div className="care-intro-content"><p className="eyebrow">A thoughtful place to begin</p><h2>{area.introTitle}</h2><p className="care-intro-copy">{area.introCopy}</p>{area.slug === "stress-sleep" && <div className={redesignStyles.introBooking}><p>Ready to feel more rested and supported? Schedule your visit and explore a personalized approach to stress, sleep, and recovery.</p><a className="button button-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">BOOK <ArrowIcon /></a></div>}</div></div></section>}
  <section className="section-pad care-conditions-section"><div className="container"><div className="care-section-heading"><p className="eyebrow">Conditions and concerns</p><h2>What may bring you in.</h2><p>{useDirectConditionCards ? "Explore common concerns and how acupuncture may fit into supportive care." : "Turn a card to see common symptoms and how acupuncture may fit into supportive care."}</p></div>{useDirectConditionCards ? <WomensConditionCards conditions={area.conditions} details={conditionDetails}/> : <div className="care-condition-grid">{area.conditions.map((condition)=><ConditionFlipCard key={condition} title={condition} detail={conditionDetails[condition]} />)}</div>}</div></section>
  {area.slug === "pain-management" && <PainTreatmentPath/>}
  {area.slug === "womens-health-fertility" ? null : <><section className="section-pad care-why-section"><div className="container care-why-grid"><div><p className="eyebrow">Why consider acupuncture?</p><h2>{area.whyTitle}</h2></div><div>{area.whyCopy.map((copy)=><p key={copy}>{copy}</p>)}</div></div></section><section className="section-pad care-evidence-section"><div className="container"><div className="care-evidence-heading"><p className="eyebrow">Science in context</p><h2>{area.evidenceTitle}</h2><p>{area.evidenceIntro}</p></div><div className="care-evidence-grid">{area.evidence.map(item=><article key={item.metric}><strong>{item.metric}</strong><p>{item.detail}</p><a href={item.sourceUrl} target="_blank" rel="noreferrer">Read source · {item.sourceLabel} <ArrowIcon/></a></article>)}</div></div></section></>}
  <section className="section-pad care-visit-section"><div className="container"><div className="care-section-heading"><p className="eyebrow">Your visit at Springwell</p><h2>Personalized care, step by step.</h2><p>Every plan is adjusted to your symptoms, health history, comfort, and goals.</p></div><div className="care-visit-grid">{area.visitSteps.map((step,index)=><article key={step.title}><span className="care-visit-number">0{index+1}</span><h3>{step.title}</h3><p>{step.text}</p><small>{step.tools}</small></article>)}</div><div className="care-visit-action"><a className="button button-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">Book Your Visit <ArrowIcon/></a></div></div></section>
  {area.clinicalNote && <section className="care-note-section"><div className="container"><p><strong>Important:</strong> {area.clinicalNote}</p></div></section>}
  {area.slug === "womens-health-fertility" && <WomensFaq/>}
  <AppointmentOptions/>
  <TalkSection/>
  </PageShell>}
