import type { Metadata } from "next";
import Image from "next/image";
import { notFound, permanentRedirect } from "next/navigation";
import { ArrowIcon } from "../../components/icons";
import { PageShell } from "../../components/site-shell";
import { site } from "../../config/site";
import { careAreas, conditionDetails, getCareArea } from "../care-data";
import { ConditionFlipCard } from "../condition-flip-card";
import { WomensConditionCards } from "../womens-condition-cards";
import { CycleTreatmentSection } from "../cycle-treatment-section";
import womensStyles from "./womens-health-sections.module.css";
import redesignStyles from "./care-redesign.module.css";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return careAreas.map((area)=>({slug:area.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const area=getCareArea(slug);if(!area)return{};return{title:area.seoTitle,description:`${area.summary} Learn about individualized acupuncture care at Springwell Acupuncture in Northern Virginia.`,alternates:{canonical:`/care/${area.slug}`}}}
function AppointmentOptions(){return <section className="section-pad care-appointment-options"><div className="container"><div className="section-heading centered-heading"><p className="eyebrow">Appointment options</p><h2>Simple, unhurried visits.</h2></div><div className="care-appointment-grid"><article><span>New patient</span><h3>Initial consultation + treatment</h3><strong>60–75 min</strong><p>A detailed intake, focused assessment, first treatment, and recommended next steps.</p><a className="text-link" href={site.bookingUrl} target="_blank" rel="noreferrer">Book your first visit <ArrowIcon/></a></article><article><span>Returning patient</span><h3>Follow-up care</h3><strong>45–60 min</strong><p>A progress check, updated treatment focus, and care shaped around your response.</p><a className="text-link" href={site.bookingUrl} target="_blank" rel="noreferrer">Book a follow-up <ArrowIcon/></a></article></div></div></section>}
function NewPatientOffer(){return <section className="care-new-patient-offer" aria-labelledby="new-patient-offer-title"><div className="container care-new-patient-offer-inner"><div><p className="eyebrow">New patient offer</p><h2 id="new-patient-offer-title">$50 off your first visit.</h2></div><div className="care-new-patient-offer-copy"><p>Begin with a comprehensive consultation and personalized acupuncture treatment for <strong>$95</strong>, regularly $145.</p><small>Available to new patients for one initial visit. Cannot be combined with other offers.</small></div><a className="button button-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">Claim $50 off <ArrowIcon/></a></div></section>}
function TalkSection(){return <section className="care-talk-section"><div className="container"><p className="eyebrow">Have questions?</p><h2>Want to talk?</h2><p>We are offering a free 15-minute consultation for those who are seeking more answers.</p><a className="button button-light" href={site.bookingUrl} target="_blank" rel="noreferrer">Book now <ArrowIcon/></a></div></section>}
const womensHealthDetails = [
  { number: "01", title: "Specialized Training in Women’s Health", copy: "Care at Springwell is informed by graduate training in Traditional Chinese Medicine gynecology. This specialized training shapes our approach to menstrual health, cycle-related symptoms, and changing needs across different stages of life." },
  { number: "02", title: "Traditional Medicine with a Modern Perspective", copy: "Springwell combines traditional Chinese medicine training with a biomedical and research-informed perspective. Treatment is rooted in traditional principles while also considering your medical history, current care, safety, and current evidence around acupuncture." },
  { number: "03", title: "Care Across Hormonal Transitions", copy: "Symptoms may change across the menstrual cycle and through perimenopause. Treatment is adapted to the concerns affecting your daily life rather than relying on a fixed women’s health protocol." },
  { number: "04", title: "Looking Beyond a Single Symptom", copy: "At Springwell, we consider the broader clinical picture. Menstrual concerns, sleep, stress, digestion, pain, and overall wellbeing may overlap, so treatment looks beyond a single symptom when developing an individualized plan." },
] as const;
function WomensHealthDetails(){const left=womensHealthDetails.slice(0,2);const right=womensHealthDetails.slice(2);const renderCard=(card:(typeof womensHealthDetails)[number])=><article key={card.number}><span>{card.number}</span><h3>{card.title}</h3><p>{card.copy}</p></article>;return <section className={womensStyles.detailsSection} aria-labelledby="why-choose-springwell-details"><div className="container"><div className={womensStyles.sectionHeading}><p className="eyebrow">An individualized approach</p><h2 id="why-choose-springwell-details">Why Choose Springwell</h2></div><div className={womensStyles.detailsLayout}><div className={womensStyles.detailsColumn}>{left.map(renderCard)}</div><div className={womensStyles.detailsImage}><Image src="/images/womens-health-specialty.webp" alt="Women representing different stages of women’s health" fill quality={90} sizes="(max-width: 860px) 100vw, 34vw" /></div><div className={womensStyles.detailsColumn}>{right.map(renderCard)}</div></div></div></section>}
function PainTreatmentPath(){return <section className="section-pad pain-treatment-path"><div className="container"><div className="care-section-heading"><p className="eyebrow">A focused pain-relief plan</p><h2>Targeted treatment for pain, tension, and movement.</h2><p>Acupuncture can work on several parts of a pain pattern at once: local sensitivity, muscle guarding, nervous-system processing, and the movement habits that keep symptoms going. Many patients notice changes in pain or mobility over a short series of visits, while results vary by condition and person.</p></div><div className="pain-path-grid"><article><span>01</span><h3>Assess the pattern</h3><p>We identify where the pain is, what triggers it, how it changes movement, and whether the symptoms need medical, dental, or physical-therapy evaluation.</p></article><article><span>02</span><h3>Use acupuncture precisely</h3><p>Needles are selected for the painful area and the broader pattern. Local and distal points may be combined to reduce sensitivity and muscle guarding.</p></article><article><span>03</span><h3>Add electroacupuncture</h3><p>For selected chronic or muscular pain patterns, a gentle rhythmic electrical stimulus can extend the treatment input without adding more needles.</p></article><article><span>04</span><h3>Release with cupping</h3><p>When tightness or soreness is prominent, cupping may be added to create a focused decompression and mobility-focused finish.</p></article></div></div></section>}
function StressDomains(){return <section className={redesignStyles.domains}><div className="container"><div className={redesignStyles.domainHeading}><p className="eyebrow">Three connected areas</p><h2>Care that follows the whole pattern.</h2></div><div className={redesignStyles.domainGrid}><article><span>01</span><h3>Stress & nervous-system regulation</h3><p>Support for overwhelm, anxious tension, jaw clenching, and difficulty shifting out of constant demand.</p></article><article><span>02</span><h3>Sleep</h3><p>Care for difficulty falling asleep, waking during the night, restless energy, and unrefreshing rest.</p></article><article><span>03</span><h3>Digestive comfort</h3><p>A whole-person approach to bloating, appetite changes, nausea, and bowel changes that may intensify with stress.</p></article></div></div></section>}
function StressBenefitIcon({type}:{type:"calm"|"release"|"sleep"}){return <span className={redesignStyles.benefitIcon} aria-hidden="true">{type==="calm"?<svg viewBox="0 0 48 48"><path d="M24 38c-8-3-13-8-14-15 6 0 11 2 14 7 3-5 8-7 14-7-1 7-6 12-14 15Z"/><path d="M24 30c-6-3-10-8-10-14 5 1 8 3 10 7 2-4 5-6 10-7 0 6-4 11-10 14Z"/><path d="M24 23c-3-3-4-7 0-12 4 5 3 9 0 12Z"/></svg>:type==="release"?<svg viewBox="0 0 48 48"><path d="M14 33c5 4 12 5 18 2 5-2 7-6 5-9-2-3-5-2-8 0l-5 3"/><path d="M16 34c-4-4-5-9-2-13l8-11c1-2 4-2 5 0 1 1 1 3 0 5l-4 6 4-3c2-1 4 0 5 2"/></svg>:<svg viewBox="0 0 48 48"><path d="M34 32c-10 2-19-5-19-15 0-3 1-5 2-7-6 3-10 9-10 16 0 9 7 16 16 16 7 0 13-4 16-10-2 0-3 0-5 0Z"/></svg>}</span>}
function StressWhyBenefits(){const benefits=[{type:"calm" as const,title:"Calms the nervous system",copy:"Helps reduce the body’s stress response and promotes relaxation."},{type:"release" as const,title:"Releases tension",copy:"Supports tight muscles, jaw clenching, and physical discomfort."},{type:"sleep" as const,title:"Improves sleep",copy:"Helps you fall asleep easier, stay asleep longer, and wake more refreshed."}];return <><section className={redesignStyles.stressWhy} aria-labelledby="stress-why-title"><div className="container"><div className={redesignStyles.stressWhyHeading}><p className="eyebrow">Why consider acupuncture?</p><h2 id="stress-why-title">Why consider acupuncture?</h2></div><div className={redesignStyles.benefitGrid}>{benefits.map((benefit)=><article key={benefit.title}><StressBenefitIcon type={benefit.type}/><div><h3>{benefit.title}</h3><p>{benefit.copy}</p></div></article>)}</div><p className={redesignStyles.stressWhyStatement}><em>A physical signal to slow down—releasing tension, deepening the breath, and quieting the mind.</em></p></div></section><section className={redesignStyles.earSeeds} aria-labelledby="ear-seeds-title"><div className="container"><div className={redesignStyles.earSeedsInner}><div><p className="eyebrow">Support between appointments</p><h2 id="ear-seeds-title">Ear seeds for between-visit support</h2></div><p>Small, adhesive ear seeds provide gentle acupressure that you can activate throughout the day. They offer a simple way to reinforce relaxation, ease restlessness, and support a calmer rhythm between acupuncture visits.</p></div></div></section></>}
const fertilityFaqs=[
  ["When should acupuncture begin before IVF?","There is no single schedule that fits every patient. Some begin before a treatment cycle; others seek support during an active cycle. Timing should fit your reproductive specialist’s plan, symptoms, and practical availability."],
  ["Can acupuncture be used during an IVF cycle?","It may be used as supportive care when your reproductive team is informed. Treatment is adjusted around medications, procedures, symptoms, and your clinic’s instructions."],
  ["How often should I come?","Frequency depends on what brings you in, your treatment stage, response, and schedule. We discuss a realistic recommendation after the first assessment and adjust it over time."],
  ["How can acupuncture support a fertility treatment cycle?","Treatment may be timed around preparation, stimulation, retrieval, transfer, and recovery, with a focus on comfort, stress regulation, sleep, muscle tension, and the day-to-day experience of care."],
  ["Can I come during menstruation?","Acupuncture can generally be adapted during menstruation. Tell your acupuncturist about heavy bleeding, severe or changing pain, pregnancy possibility, medications, and relevant diagnoses."],
  ["Should I tell my fertility specialist?","Yes. Keeping every clinician informed helps coordinate care, avoid conflicts, and ensure that symptoms or medication effects receive appropriate attention."],
] as const;
const womensFaqs=[
  ["Can acupuncture be used during menstruation?","Acupuncture can generally be adapted during menstruation. Tell your acupuncturist about heavy bleeding, severe or changing pain, pregnancy possibility, medications, and relevant diagnoses."],
  ["Can acupuncture help period cramps?","Some patients use acupuncture as part of a plan for pain and muscle-tension support. New, severe, or worsening cramps still deserve gynecologic evaluation."],
  ["How may acupuncture support irregular cycles?","Care is shaped around cycle timing, symptoms, stress, sleep, pain, and overall wellbeing, with progress tracked across more than one cycle."],
  ["Can I receive acupuncture if I have PCOS?","Yes. Treatment can be adapted to your cycle pattern, stress, sleep, pain, energy, and the symptoms affecting daily life."],
  ["Can acupuncture support perimenopause symptoms?","Care may focus on sleep, tension, headaches, or overall comfort during perimenopause. Treatment is individualized, and changing symptoms should also be discussed with your medical clinician."],
  ["How often should I come?","Frequency depends on the concern, symptom pattern, response, and practical schedule. We recommend a realistic starting plan after your first assessment."],
] as const;
function CareFaq({type}:{type:"womens"|"fertility"}){const items=type==="fertility"?fertilityFaqs:womensFaqs;return <section className={redesignStyles.faq}><div className="container"><div className={redesignStyles.faqHeading}><p className="eyebrow">{type==="fertility"?"Fertility support FAQ":"Women’s health FAQ"}</p><h2>{type==="fertility"?"Common questions about fertility acupuncture":"Common questions about women’s health acupuncture"}</h2></div><div className={redesignStyles.faqList}>{items.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>}
const directConditionCardSlugs = new Set(["womens-health", "fertility-ivf-support", "pain-management", "stress-sleep"]);
export default async function CareAreaPage({params}:Props){const {slug}=await params;if(slug==="womens-health-fertility")permanentRedirect("/care/womens-health");const area=getCareArea(slug);if(!area)notFound();const useDirectConditionCards=directConditionCardSlugs.has(area.slug);const isWomensHealth=area.slug === "womens-health";const isFertility=area.slug === "fertility-ivf-support";const isStress=area.slug === "stress-sleep";const introImage=isStress?"/images/stress-mind-line-illustration.webp":isFertility?"/images/fertility-journey-support.jpg":"/images/bringing-balance-back.jpeg";const introAlt=isStress?"Minimal line illustration of a person gently untangling a busy mind":isFertility?"Two women sharing a supportive moment outdoors during a hike":"Hands gently balancing a stack of smooth stones";return <PageShell><section className={`care-page-hero ${isWomensHealth ? womensStyles.hero : ""} ${isStress ? redesignStyles.stressHero : ""}`}><div className={`care-page-hero-media ${isWomensHealth ? womensStyles.heroMedia : ""} ${isStress ? redesignStyles.stressHeroMedia : ""}`}><Image src={area.image} alt={area.imageAlt} fill priority quality={isWomensHealth || isStress ? 100 : 95} unoptimized={isWomensHealth || isStress} sizes={isStress ? "(max-width: 760px) 100vw, 52vw" : "100vw"}/></div><div className={`care-page-hero-overlay ${isStress ? redesignStyles.stressHeroOverlay : ""}`}/><div className={`container care-page-hero-content ${isStress ? redesignStyles.stressHeroContent : ""}`}><p className="eyebrow light">{area.eyebrow}</p><h1>{area.title}</h1><div className={womensStyles.heroSummary}>{area.summary.split("\n\n").map((paragraph)=><p key={paragraph}>{paragraph}</p>)}</div><a className="button button-light" href={site.bookingUrl} target="_blank" rel="noreferrer">Book your first visit <ArrowIcon/></a></div></section>
  <NewPatientOffer/>
  {area.slug === "stress-sleep" && <StressDomains/>}
  {isWomensHealth ? <><CycleTreatmentSection/><WomensHealthDetails/></> : area.slug === "pain-management" ? null : <section className="section-pad care-intro-section"><div className="container care-intro-image-grid"><div className={`care-intro-image ${isStress ? redesignStyles.stressIntroImage : ""} ${isFertility ? "care-intro-image-fertility" : ""}`}><Image src={introImage} alt={introAlt} className={isStress ? redesignStyles.stressIntroArtwork : undefined} fill quality={92} sizes="(max-width: 860px) 100vw, 42vw" /></div><div className="care-intro-content"><p className="eyebrow">A thoughtful place to begin</p><h2>{area.introTitle}</h2><p className="care-intro-copy">{area.introCopy}</p>{isStress && <div className={redesignStyles.introBooking}><p>Ready to feel more rested and supported? Schedule your visit and explore a personalized approach to stress, sleep, and recovery.</p><a className="button button-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">BOOK <ArrowIcon /></a></div>}</div></div></section>}
  <section className="section-pad care-conditions-section"><div className="container"><div className="care-section-heading"><p className="eyebrow">Conditions and concerns</p><h2>What may bring you in.</h2><p>{useDirectConditionCards ? "Explore common concerns and how acupuncture may fit into supportive care." : "Turn a card to see common symptoms and how acupuncture may fit into supportive care."}</p></div>{useDirectConditionCards ? <WomensConditionCards conditions={area.conditions} details={conditionDetails} detailed={isFertility} womensLayout={isWomensHealth} symptomLabel={isStress ? "Common symptoms" : undefined}/> : <div className="care-condition-grid">{area.conditions.map((condition)=><ConditionFlipCard key={condition} title={condition} detail={conditionDetails[condition]} />)}</div>}</div></section>
  {area.slug === "pain-management" && <PainTreatmentPath/>}
  {isStress ? <StressWhyBenefits/> : !isWomensHealth && <section className="section-pad care-why-section"><div className="container care-why-grid"><div><p className="eyebrow">Why consider acupuncture?</p><h2>{area.whyTitle}</h2></div><div>{area.whyCopy.map((copy)=><p key={copy}>{copy}</p>)}</div></div></section>}
  {!isWomensHealth && !isFertility && <section className="section-pad care-evidence-section"><div className="container"><div className="care-evidence-heading"><p className="eyebrow">Science in context</p><h2>{area.evidenceTitle}</h2><p>{area.evidenceIntro}</p></div><div className="care-evidence-grid">{area.evidence.map(item=><article key={item.metric}><strong>{item.metric}</strong><p>{item.detail}</p><a href={item.sourceUrl} target="_blank" rel="noreferrer">Read source · {item.sourceLabel} <ArrowIcon/></a></article>)}</div></div></section>}
  <section className="section-pad care-visit-section"><div className="container"><div className="care-section-heading"><p className="eyebrow">Your visit at Springwell</p><h2>Personalized care, step by step.</h2><p>Every plan is adjusted to your symptoms, health history, comfort, and goals.</p></div><div className="care-visit-grid">{area.visitSteps.map((step,index)=><article key={step.title}><span className="care-visit-number">0{index+1}</span><h3>{step.title}</h3><p>{step.text}</p><small>{step.tools}</small></article>)}</div><div className="care-visit-action"><a className="button button-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">Book Your Visit <ArrowIcon/></a></div></div></section>
  {isWomensHealth && <CareFaq type="womens"/>}
  {isFertility && <CareFaq type="fertility"/>}
  <AppointmentOptions/>
  <TalkSection/>
  </PageShell>}
