export const site = {
  name: "SpringWell Acupuncture",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://springwellacu.com",
  bookingUrl:
    process.env.NEXT_PUBLIC_BOOKING_URL ||
    "https://app.squareup.com/appointments/book/4j5cnvy44yi5kt/L9E4KW7SXV9DE/start",
  description:
    "Holistic Care. Acupuncture. 463 Carlisle Dr, Suite B, Second Floor, Herndon, VA 20170. Personalized care for women’s health, fertility, pain, stress, sleep, and digestion.",
  email: "info@springwellacu.com",
  phone: "703-495-2857",
  phoneHref: "tel:+17034952857",
  address: "463 Carlisle Dr, Suite B, Second Floor, Herndon, VA 20170",
  streetAddress: "463 Carlisle Dr, Suite B, Second Floor",
  addressLocality: "Herndon",
  addressRegion: "VA",
  postalCode: "20170",
  directionsUrl: "https://www.google.com/maps/search/?api=1&query=springwell+acupuncture",
  mapEmbedUrl: "https://www.google.com/maps?q=springwell%20acupuncture&output=embed",
  hours: {
    days: "Tuesday, Thursday, Friday & Sunday",
    time: "9:00 AM–5:30 PM",
    opens: "09:00",
    closes: "17:30",
  },
  socialLinks: [
    {
      label: "Instagram",
      handle: "@springwell_acupuncture",
      href: "https://www.instagram.com/springwell_acupuncture/",
    },
  ],
  serviceArea: [
    "Herndon",
    "Reston",
    "Northern Virginia",
    "McLean",
    "Falls Church",
    "Fairfax",
    "Vienna",
    "Tysons",
    "Arlington",
    "Alexandria",
    "Washington DC",
    "Bethesda",
    "Rockville",
    "Silver Spring",
  ],
  seoKeywords: [
    "SpringWell Acupuncture",
    "Springwell Acupuncture Herndon",
    "acupuncture Herndon VA",
    "holistic care Herndon Virginia",
    "Northern Virginia acupuncture",
    "DMV acupuncture clinic",
    "fertility acupuncture Northern Virginia",
    "IVF acupuncture support",
    "women's health acupuncture Northern Virginia",
    "pain management acupuncture",
    "TMJ acupuncture",
    "orofacial pain acupuncture",
    "stress and sleep acupuncture",
    "digestive health acupuncture",
    "cupping Northern Virginia",
    "Chinese herbal medicine Northern Virginia",
  ],
} as const;
