import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowIcon } from "../components/icons";
import { CurrencyMark } from "../components/currency-mark";
import { PageShell } from "../components/site-shell";
import { site } from "../config/site";
import styles from "./new-patients.module.css";

export const metadata: Metadata = { title: "New Patients | Springwell Acupuncture", description: "What to expect, visit pricing, payment information, and how to prepare for your first acupuncture appointment in Herndon, Virginia." };

export default function NewPatientsPage(){return <PageShell>
  <section className={styles.hero}><div className={`container ${styles.heroGrid}`}><div><p className="eyebrow">New patients</p><h1>Your first visit, without the guesswork.</h1><p>Understand what happens, how to prepare, and what your visit costs before you schedule.</p><Link className="button button-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">Book your first visit <ArrowIcon /></Link></div><div className={styles.heroImage}><Image src="/images/first-session-assessment.webp" alt="A thoughtful first-visit health assessment" fill priority sizes="(max-width: 800px) 100vw, 48vw" /></div></div></section>
  <section className="care-new-patient-offer" aria-labelledby="new-patient-page-offer-title"><div className="container care-new-patient-offer-inner"><div><p className="eyebrow">New patient offer</p><h2 id="new-patient-page-offer-title">$50 off your first visit.</h2></div><div className="care-new-patient-offer-copy"><p>Begin with a comprehensive consultation and personalized acupuncture treatment for <strong>$95</strong>, regularly $145.</p><small>Available to new patients for one initial visit. Cannot be combined with other offers.</small></div><Link className="button button-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">Claim $50 off <ArrowIcon /></Link></div></section>
  <section className={styles.section}><div className="container"><div className={styles.heading}><p className="eyebrow">Your first visit</p><h2>Three simple steps</h2></div><div className={styles.steps}><article><span>01</span><h3>Book online</h3><p>Choose an available initial appointment through our secure scheduling page.</p></article><article><span>02</span><h3>Complete your intake</h3><p>Share your concerns, health history, medications, and current care before arriving.</p></article><article><span>03</span><h3>Meet and begin treatment</h3><p>We review your goals, complete a focused assessment, and provide an individualized acupuncture treatment.</p></article></div></div></section>
  <section className={`${styles.section} ${styles.pricing}`}><div className={`container ${styles.priceGrid}`}><div><p className="eyebrow">Pricing</p><h2>Clear costs before you arrive</h2><p>Visits are unhurried and include time to discuss your response and next steps.</p></div><div className={styles.prices}><article><div><span>Initial visit</span><strong><CurrencyMark />145</strong></div><p>Consultation + acupuncture treatment · approximately 60–75 minutes</p></article><article><div><span>Follow-up visit</span><strong><CurrencyMark />95</strong></div><p>Progress review + acupuncture treatment · approximately 45–60 minutes</p></article><article><div><span>Cupping</span><strong><CurrencyMark />50</strong></div><p>Focused cupping session · approximately 30 minutes</p></article></div></div></section>
  <section className={styles.section}><div className={`container ${styles.prepareGrid}`}><div className={styles.prepareImage}><Image src="/images/first-session-rest.webp" alt="A patient resting comfortably during acupuncture" fill sizes="(max-width: 800px) 100vw, 45vw" /></div><div><p className="eyebrow">Before your appointment</p><h2>A little preparation helps.</h2><ul><li>Eat a light meal and stay hydrated before your visit.</li><li>Wear loose, comfortable clothing when possible.</li><li>Bring a list of medications and relevant diagnoses or procedures.</li><li>Continue prescribed care unless your medical provider advises otherwise.</li><li>Plan a few extra minutes for arrival and settling in.</li></ul><Link className="text-link" href="/faq">Read frequently asked questions <ArrowIcon /></Link></div></div></section>
  <section className={styles.insurance}><div className="container"><p className="eyebrow">Insurance & payment</p><h2>Self-pay care with superbill support</h2><p>Springwell currently welcomes self-pay patients and is pursuing participation with selected insurance networks. We can provide a superbill for you to submit for possible out-of-network reimbursement; benefits and reimbursement are determined by your plan.</p><Link className="button button-secondary" href="/pricing#insurance">Review payment details <ArrowIcon /></Link></div></section>
  <section className={styles.cta}><div className="container"><p className="eyebrow light">Ready when you are</p><h2>Begin with a thoughtful conversation and individualized care.</h2><Link className="button button-light" href={site.bookingUrl} target="_blank" rel="noreferrer">Book an appointment <ArrowIcon /></Link></div></section>
  </PageShell>}
